### ISSUE TITLE
Can't search for users

### ISSUE THREAD

**Issue by KLNorthdegree** [OllieTerrance/SkyPy#5]
http://i.imgur.com/iYhAoeH.png

You can't search for users using the SkypeContacts class. It expects an SkypeContacts instance as first parameter which is... well, not meant to be like that.

**Comment by OllieTerrance** [comment]
`SkypeContacts.contact(...)` is not a static method, you need to use an instance of `SkypeContacts` as it requires an authenticated connection to Skype.

If `args[0]` is a username, you should actually be using `sk.contacts[args[0]]` (where `sk` is an instance of `Skype`) -- this will do the necessary contact or user lookups as needed.  If you're searching by name, use `sk.contacts.search(args[0])` to get some possible matches.

```python
sk = Skype(...)
contact = sk.contacts["joe.4"] # returns a SkypeContact if a contact, otherwise SkypeUser
results = sk.contacts.search("Joe Bloggs") # list of dicts of results
```
